version: "3.8"

services:

  accounts:
    image: bobmwas/mufasa:accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - mufasa-network
      
  loans:
    image: bobmwas/mufasa:loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - mufasa-network
      
  cards:
    image: bobmwas/mufasa:cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - mufasa-network
      
networks:
  mufasa-network: