version: "3.8"

services:
  configs:
    image: bobmwas/mufasa:configs
    mem_limit: 700m
    ports:
      - "8071:8071"    
    networks:
      - mufasa
      
  accounts:
    image: bobmwas/mufasa:accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - mufasa
    depends_on:
      - configs  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/      
      
  loans:
    image: bobmwas/mufasa:loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - mufasa
    depends_on:
      - configs  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/      
      
  cards:
    image: bobmwas/mufasa:cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - mufasa
    depends_on:
      - configs  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/          
      
networks:
  mufasa: