version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - mufasa
      
  configs:
    image: bobmwas/mufasa:configs
    mem_limit: 700m
    ports:
      - "8071:8071"    
    networks:
      - mufasa
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/   
      
  eurekaserver:
    image: bobmwas/mufasa:eurekaserver
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - mufasa
    depends_on:
      - configs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/       
      
  accounts:
    image: bobmwas/mufasa:accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - mufasa
    depends_on:
      - configs 
      - eurekaserver 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/       
      
  loans:
    image: bobmwas/mufasa:loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - mufasa
    depends_on:
      - configs  
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/      
      
  cards:
    image: bobmwas/mufasa:cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - mufasa
    depends_on:
      - configs  
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/ 
      
  gatewayserver:
    image: bobmwas/mufasa:gatewayserver
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - mufasa
    depends_on:
      - configs  
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment: 
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/                 
      
networks:
  mufasa: