version: "3.8"

services:
  configs:
    image: bobmwas/mufasa:configs
    mem_limit: 700m
    ports:
      - "8071:8071"    
    networks:
      - mufasa
      
  eurekaserver:
    image: bobmwas/mufasa:eurekaserver
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - mufasa
    depends_on:
      - configs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/         
      
  accounts:
    image: bobmwas/mufasa:accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - mufasa
    depends_on:
      - configs  
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/      

            
  loans:
    image: bobmwas/mufasa:loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - mufasa
    depends_on:
      - configs  
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/      
      
  cards:
    image: bobmwas/mufasa:cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - mufasa
    depends_on:
      - configs  
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment: 
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configs:8071/ 
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/         
      
networks:
  mufasa: